### ISSUE TITLE
"Please connect to the internet" but i have internet?

### ISSUE THREAD

**Issue by berkerentepe** [JohandeGraaf/LoLFlavor-Sync#1]
I have network connection but this program saying "Please connect to the internet"?

**Comment by JohandeGraaf** [comment]
Hi,

To understand where this problem is coming from; please do the following when the bug occurs again:
-  First make sure you are connected to the internet. If it still says "Please connect to the internet?" continue with the steps below.
-  Open the Command Prompt, you can either do this by searching for it in the start menu, or pressing Windows key + X and pressing "Command Prompt"
-  Copy and paste this line into the command prompt and press enter:

`Powershell -Command "Add-Type -assembly Microsoft.VisualBasic; $N = New-Object Microsoft.VisualBasic.Devices.Network; $N.IsAvailable"`

Let me know what the output of that command is, it will give either 'True' or 'False'

**Comment by berkerentepe** [comment]
Hi,

The result is true.

2015-09-13 21:53 GMT+03:00 Johan de Graaf notifications@github.com:

**Comment by JohandeGraaf** [comment]
I think I know where the problem is, I will fix the bug it in the next release which should be this week or early next week. Thanks for your help!
